### ISSUE TITLE
nccl-repo.deb: no such file or directory

### ISSUE THREAD

**Issue by hongthana** [jens-froeschel/wav2vec-docker-training#1]
Hello Jens,

First of all, thank you for creating this docker file. I've tried to train Thai language on wav2vec 2.0. But I have no luck on training the model. Luckily, I found your git and tried to install the docker file. However, it seems like the nccl is missing.

Could you advise me what I need to do?

```
Step 8/14 : COPY  nccl-repo.deb /data/nccl-install.deb
COPY failed: stat /var/lib/docker/tmp/docker-builder727592787/nccl-repo.deb: no such file or directory
```

**Comment by jens-froeschel** [comment]
Hello Hongthana,

The problem is that NCCL is proprietary and therefore I am not allowed to share it on the repository.

The steps you have to do is basically the Installation steps from the Readme:
- Retrieve NVIDIA NCCL Local Installer for Debian Ubuntu1804 & Cuda Version 10.2 from here https://developer.nvidia.com/nccl/getting_started -> Download NCCL (you must Login with an NVidia Developer Account or create an NVidia Developer Account if you don't yet have one)
- Rename the NCCL Installer Debian package to "nccl-repo.deb"
